# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Streamr Docker Dev Action'
description: 'Start Streamr Docker Stack'
branding:
  icon: 'layers'
  color: 'orange'
inputs:
  services-to-start:
    description: 'Streamr Docker Stack services to start'
    required: false
    # If changing the default list of services below, update examples in README.md
    default: 'mysql redis engine-and-editor cassandra parity-node0 parity-sidechain-node0 bridge data-union-server broker-node-storage-1 nginx smtp platform'
runs:
  using: "composite"
  steps:
    - run: |
          git clone --depth 1 https://github.com/streamr-dev/streamr-docker-dev.git
          cp streamr-docker-dev/streamr-docker-dev/bin.sh streamr-docker-dev/streamr-docker-dev/streamr-docker-dev
          echo "$(pwd)/streamr-docker-dev/streamr-docker-dev" >> $GITHUB_PATH
          sudo ifconfig docker0 10.200.10.1/24
      shell: bash
    - run: |
          streamr-docker-dev start ${{ inputs.services-to-start }}
          streamr-docker-dev wait
      shell: bash
