# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Streamr Docker Dev Action'
description: 'Start Streamr Docker Stack'
author: 'streamr-dev'
branding:
  icon: 'layers'
  color: 'orange'
inputs:
  services:
    description: 'Streamr Docker Stack services to start'
    required: false
    # If changing the default list of services below, update examples in README.md
    default: 'mysql redis engine-and-editor cassandra parity-node0 parity-sidechain-node0 bridge data-union-server broker-node-storage-1 nginx smtp platform'
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'
