name: 'Streamr Docker Dev Action'
description: 'Start Streamr Docker Stack'
branding:
  icon: 'layers'
  color: 'orange'
inputs:
  services-to-start:
    description: 'Streamr Docker Stack services to start'
    required: false
    # If changing the default list of services below, update examples in README.md
    default: 'mysql redis core-api cassandra parity-node0 parity-sidechain-node0 bridge data-union-server broker-node-storage-1 nginx smtp platform'
  branch-to-use:
    description: 'Streamr Docker Branch to Use'
    required: false
    default: 'master'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2.3.5
      with:
        repository: streamr-dev/streamr-docker-dev
        ref: ${{ inputs.branch-to-use }}
        path: streamr-docker-dev
    - run: |
          cp streamr-docker-dev/streamr-docker-dev/bin.sh streamr-docker-dev/streamr-docker-dev/streamr-docker-dev
          echo "$(pwd)/streamr-docker-dev/streamr-docker-dev" >> $GITHUB_PATH
      shell: bash
    - run: |
          streamr-docker-dev start ${{ inputs.services-to-start }}
          streamr-docker-dev wait
      shell: bash
