on: [push]
name: Continuous Integration
jobs:
  ci:
    runs-on: ubuntu-latest
    name: Testing streamr-docker-dev-action
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: streamr-dev/streamr-docker-dev-action@dev-start-wait-attributes
    - name: 'Test'
      run: curl -v http://localhost/api/v1/products
      shell: bash
