on: [push]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing streamr-docker-dev-action
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Login to DockerHub
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: ./
    - run: |
        docker pull streamr/redis:v0.0.1
        curl -v http://localhost/api/v1/products
      shell: bash
