on: [push]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing streamr-docker-dev-action
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: ./
      with:
        dockerhub_username: foobar
        dockerhub_token: secret-token
    - run: curl -v http://localhost/api/v1/products
      shell: bash
