on: [push]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing streamr-docker-dev-action
    steps:
    - uses: actions/checkout@v3
    - uses: ./
    - run: curl -v http://localhost/api/v1/products
      shell: bash
