on: [push]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing streamr-docker-dev-action
    steps:
    - uses: actions/checkout@v2
    - uses: streamr-dev/streamr-docker-dev-action@master
      with:
        services-to-start: 'redis'
    - run: curl -v http://localhost/api/v1/products
      shell: bash
